### ISSUE TITLE
Dependency on 'unzip'

### ISSUE THREAD

**Issue by EricEttes** [example42/puppet-jboss#31]
The plugin seems to rely on 'unzip', which isn't installed by default on a clean ubuntu image. 

I'm using Vagrant 1.6.2 / Puppet 3.5.1 with this box: https://vagrantcloud.com/puppetlabs/ubuntu-12.04-64-puppet

Current workaround is adding the necessary provisioning in my Vagrantfile

**Comment by b-long** [comment]
:+1: Same issue.  What's worse, there doesn't seem to be a canonical 'unzip' puppet module.  To increase adoption of this module, I'd recommend removing the 'unzip' dependency.  In CentOS land, I ended up needing to add `yum -q -y install unzip`

**Comment by alvagante** [comment]
Yes, unzip is used when installation is done from upgrade source.
Still I don't think a zip package should be provided in a jboss module, maybe it's just better to document this dependency somewhere.
