### ISSUE TITLE
GID error

### ISSUE THREAD

**Issue by itachi117** [example42/puppet-jboss#41]
Hi,
I'm trying to install Jboss using puppet and when I'm trying to run Puppet sync I get the following error:
"Failed to apply catalog: Parameter gid failed on Group[jboss]: Invalid GID  at /etc/puppetlabs/code/environments/production/modules/jboss/manifests/user.pp:24"

How can I resolve this problem ?

**Comment by alvagante** [comment]
Set on hiera a key like:
jboss:: user_gid with a gid that doesn't clash with existing ones

**Comment by alvagante** [comment]
FYI this commit should fix the issue (with Puppet 4):
https://github.com/example42/puppet-jboss/commit/93962fa49b7311752874f81742f60dc019ce1776
