### ISSUE TITLE
Errors while installting JBOSS

### ISSUE THREAD

**Issue by rkathpal** [example42/puppet-jboss#5]
Hi,

I am a big fan of example42 modules and using most of them, currently I am facing issues with the Jboss module

I ma using the latest jboss build from example42 and latest puppi modules as well.. but still getting the following errors

-------------------------------
info: Caching catalog for ABC
info: Applying configuration version '1358506111'
notice: /Stage[main]/Jboss::User/User[jboss]/ensure: created
notice: /Stage[main]/Jboss::Install/File[jboss_link]/ensure: created
notice: /Stage[main]/Jboss::Install/Puppi::Netinstall[netinstall_jboss]/Exec[Retrieve http://download.jboss.org/jbossas/6.1/jboss-as-distribution-6.1.0.Final.zip]/returns: executed successfully
notice: /Stage[main]/Jboss::Install/Puppi::Netinstall[netinstall_jboss]/Exec[Extract jboss-as-distribution-6.1.0.Final.zip]/returns: executed successfully
info: /Stage[main]/Jboss::Install/Puppi::Netinstall[netinstall_jboss]/Exec[Extract jboss-as-distribution-6.1.0.Final.zip]: Scheduling refresh of Exec[PostExtract jboss-as-distribution-6.1.0.Final.zip]
info: /Stage[main]/Jboss::Install/Puppi::Netinstall[netinstall_jboss]/Exec[Extract jboss-as-distribution-6.1.0.Final.zip]: Scheduling refresh of Exec[Chown jboss-as-distribution-6.1.0.Final.zip]
err: /Stage[main]/Jboss::Install/Puppi::Netinstall[netinstall_jboss]/Exec[PostExtract jboss-as-distribution-6.1.0.Final.zip]: Failed to call refresh: Working directory '/opt/jboss-as-distribution-6.1.0.Final' does not exist
err: /Stage[main]/Jboss::Install/Puppi::Netinstall[netinstall_jboss]/Exec[Chown jboss-as-distribution-6.1.0.Final.zip]: Failed to call refresh: chown -R root:root /opt/jboss-as-distribution-6.1.0.Final returned 1 instead of one of [0] at /etc/puppet/modules/puppi/manifests/netinstall.pp:118
notice: /Stage[main]/Jboss::Service/File[jboss.init]/ensure: created
notice: /Stage[main]/Jboss::Service/Service[jboss]/ensure: ensure changed 'stopped' to 'running'
notice: Finished catalog run in 49.37 seconds
-----------------------------------------------------
my node manifest is 

node 'ABC' {
class { 'jboss':
}
-----------------------------------------------------

Currently I am trying the module on centos but will need it immediately for suse/ubuntu and rhel as well....

please help..

Thanks in advance...

**Comment by parvesh262** [comment]
Hi All , 
I am trying to install Jboss  on RHEL 7.x , using puppet enterprise version > 4.x  .

Getting cyclic dependency error ..

Stage[main]/Puppet_enterprise::Profile::Mcollective::Peadmin/Puppet_enterprise::Mcollective::Client[peadmin]/Puppet_enterprise::Mcollective::Client::User[peadmin]/Pe_accounts::User[peadmin]/Pe_accounts::Home_dir[/var/lib/peadmin]/File[/var/lib/peadmin/.ssh/authorized_keys]: Adding autorequire relationship with Group[peadmin]
Debug: Storing state
Debug: Stored state in 0.14 seconds
Error: Failed to apply catalog: Found 1 dependency cycle:
(File[jboss.conf] => Service[jboss] => Class[Jboss::Service] => Class[Jboss] => File[jboss.conf])
Cycle graph written to /opt/puppetlabs/puppet/cache/state/graphs/cycles.dot.
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/simple_graph.rb:242:in `report_cycles_in_graph'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:106:in `traverse'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:142:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:221:in `block in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:155:in `with_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:118:in `as_logging_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:220:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:171:in `block in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:223:in `block in benchmark'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:222:in `benchmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:170:in `apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:315:in `run_internal'
/opt/puppetlabs/puppet/l

Dot file looks like : 
digraph Resource_Cycles {
  label = "Resource Cycles"
"File[jboss.conf]" -> "Service[jboss]" -> "Class[Jboss::Service]" -> "Class[Jboss]" -> "File[jboss.conf]"
"File[jboss.conf]" -> "Service[jboss]" -> "Class[Jboss::Service]" -> "Class[Jboss]" -> "File[jboss.dir]" -> "File[jboss.conf]"
"File[jboss.conf]" -> "Service[jboss]" -> "Class[Jboss::Service]" -> "Class[Jboss]" -> "File[jboss.dir]" -> "Service[jboss]"
}


Could you please let me how to resolve this .As i am new to this .

**Comment by alvagante** [comment]
Wheere do you declare/include  the jboss class?
In a manifest? If so, please copy here the code.
In PE node classifier? If so you do pass any further parameter (either via the web interface of via hiera) to the class?
Also do you refer to the Jboss class somewhere in your code?

**Comment by alvagante** [comment]
This commit should fix the issue:
https://github.com/example42/puppet-jboss/commit/93962fa49b7311752874f81742f60dc019ce1776
